CREATE VIEW TKNhanVien_IT AS
SELECT UserID, EmployeeID,MaPB
FROM TAIKHOAN
WHERE TAIKHOAN.MaPB='IT'

CREATE VIEW TKNhanVien_AI AS
SELECT UserID, EmployeeID,MaPB
FROM TAIKHOAN
WHERE TAIKHOAN.MaPB='AI'

CREATE VIEW TKNhanVien_HR AS
SELECT UserID, EmployeeID,MaPB
FROM TAIKHOAN
WHERE TAIKHOAN.MaPB='HR'

CREATE VIEW TKNhanVien_KD AS
SELECT UserID, EmployeeID,MaPB
FROM TAIKHOAN
WHERE TAIKHOAN.MaPB='KD'

CREATE VIEW TKNhanVien_KT AS
SELECT UserID, EmployeeID,MaPB
FROM TAIKHOAN
WHERE TAIKHOAN.MaPB='KT'

CREATE VIEW TKNhanVien_TK AS
SELECT UserID, EmployeeID,MaPB
FROM TAIKHOAN
WHERE TAIKHOAN.MaPB='TK'

CREATE VIEW TKNhanVien_TT AS
SELECT UserID, EmployeeID,MaPB
FROM TAIKHOAN
WHERE TAIKHOAN.MaPB='TT'
