INSERT INTO TAIKHOAN (UserID,EmployeeID,MaPB,PASS)
VALUES 
('NV012', 'NV012','HR','nXUoSKfji0');

DELETE dbo.TAIKHOAN WHERE UserID='NV012'

UPDATE dbo.TAIKHOAN
SET PASS ='GZnv0EEQB6'
WHERE UserID='NV010'